name: C/C++ CI

on: [push]

jobs:

  spa:
    runs-on: ubuntu-latest
    container: diagprov/clang-build:latest
    steps:
    - uses: actions/checkout@v1
    - name: clang-tidy (c89/symkey)
      run: CC=clang LD=clang E4_OUTPUT_DIR=qa/tidy/symkey CSTD=c89 CONF=symkey make tidy
    - name: clang-tidy (c89/pubkey)
      run: CC=clang LD=clang E4_OUTPUT_DIR=qa/tidy/pubkey CSTD=c89 CONF=pubkey make tidy
    - name: clang-tidy (c11/all)
      run: CC=clang LD=clang E4_OUTPUT_DIR=qa/tidy/all CSTD=c11 CONF=all make tidy

  symkey:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make clean
      run: CSTD=c89 CONF=symkey make clean
    - name: make 
      run: CSTD=c89 CONF=symkey make
    - name: make test (ASAN/UBSAN)
      run: CC=clang LD=clang E4_OUTPUT_DIR=qa/aubsan/symkey E4_CFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" E4_LDFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" CSTD=c89 CONF=symkey make test
    - name: make test (MEMSAN)
      run: CC=clang LD=clang E4_OUTPUT_DIR=qa/memsan/symkey E4_CFLAGS="-fsanitize=memory -fno-omit-frame-pointer" E4_LDFLAGS="-fsanitize=memory -fno-omit-frame-pointer" CSTD=c89 CONF=symkey make test
  
  pubkey:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make clean
      run: CSTD=c89 CONF=pubkey make clean
    - name: make
      run: CSTD=c89 CONF=pubkey make
    - name: make test (ASAN/UBSAN)
      run: CC=clang LD=clang E4_OUTPUT_DIR=qa/aubsan/pubkey E4_CFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" E4_LDFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" CSTD=c89 CONF=pubkey make test
    - name: make test (MEMSAN)
      run: CC=clang LD=clang E4_OUTPUT_DIR=qa/memsan/pubkey E4_CFLAGS="-fsanitize=memory -fno-omit-frame-pointer" E4_LDFLAGS="-fsanitize=memory -fno-omit-frame-pointer" CSTD=c89 CONF=pubkey make test
  
  all:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make clean
      run: CSTD=c89 CONF=all make clean
    - name: make
      run: CSTD=c89 CONF=all make
    - name: make test (ASAN/UBSAN)
      run: CC=clang LD=clang E4_OUTPUT_DIR=qa/aubsan/all E4_CFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" E4_LDFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" CSTD=c89 CONF=all make test
    - name: make test (MEMSAN)
      run: CC=clang LD=clang E4_OUTPUT_DIR=qa/memsan/all E4_CFLAGS="-fsanitize=memory -fno-omit-frame-pointer" E4_LDFLAGS="-fsanitize=memory -fno-omit-frame-pointer" CSTD=c89 CONF=all make test
